# Generated by Django 3.2.8 on 2021-11-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211016_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikelz',
            options={'ordering': ['-date'], 'verbose_name_plural': 'artikel'},
        ),
    ]
