# Generated by Django 3.2.8 on 2021-12-05 08:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_artikelz_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikelz',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
